config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'phones_wiki#brands'

  scope '/wiki' do
    get '/' => 'phones_wiki#brands', as: 'brands'
    get '/:brand_id' => 'phones_wiki#phones', as: 'phones'
    get '/:brand_id/new' => 'phones_wiki#new', as: 'new_phone'
    get '/:brand_id/:id' => 'phones_wiki#show', as: 'phone'
    get '/:brand_id/:id/edit' => 'phones_wiki#edit', as: 'edit_phone'
    post '/:brand_id' => 'phones_wiki#show', as: 'create_phone'
    patch '/:brand_id/:id' => 'phones_wiki#update', as: 'update_phone'
    delete '/:brand_id/:id' => 'phones_wiki#destroy', as: 'destroy_phone'
  end

  get '/collections' => 'index#collections', as: 'collections'
end

app/models/brand.rb
class Brand < ActiveRecord::Base
  has_many :phones
end

app/models/phone.rb
class Phone < ActiveRecord::Base
  belongs_to :brand
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/phones_wiki_controller.rb
class PhonesWikiController < ApplicationController
  before_action :set_phone, only: [:show, :edit, :update, :destroy]
  #before_action :check_auth, only: [:edit, :update, :destroy, :create, :new]
  before_action :set_brand, only: [:index, :new, :create]

  def brands
    @brands = Brand.all
  end

  def phones
    @brand = Brand.find(params[:brand_id])
    @phones = @brand.phones.order(:created_at)
  end

  def show
  end

  def new
    @phone = Phone.new
  end

  def edit
  end

  def create
    @phone = Phone.new(phone_params)
    @phone.brand = @brand

    if @phone.save
      redirect_to phone_path(@brand, @phone), notice: 'Phone was successfully created.'
    else
      render :new
    end
  end

  def update
    if @phone.update(phone_params)
      redirect_to phone_path(@brand, @phone), notice: 'Phone was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @phone.destroy
    redirect_to phones_url(@brand), notice: 'Phone was successfully destroyed.'
  end

  private
    def check_auth
      return redirect_to phones_path(@brand), notice: "You have no rights to do it" unless current_user.present?
    end

    def set_phone
      @phone = Phone.find(params[:id])
      @brand = @phone.brand
    end

    # Only allow a trusted parameter "white list" through.
    def phone_params
      params.require(:phone).permit(:name, :network, :features, :weight, :size, :akkum, :limited, :notes, :photo_url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Phones Collection</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <div class="left">
      <h4 class="left"><%= link_to "Phones Collection", root_path %></h4>
      <div class="menu left">
        <%= link_to "collections list", '' %>
      </div>
    </div>
    <div class="right">
      <% if signed_in? %>
        <%= current_user.email %> || <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
      <% else %>
        <%= link_to "Sign in", new_user_session_path %>
      <% end %>
    </div>
  </header>

  <div id="content">
    <%= yield %>
  </div>
</body>
</html>

app/views/phones_wiki/_form.html.slim
= simple_form_for(@phone, url: update_phone_path(@brand, @phone)) do |f|
  = f.error_notification

  div{class="form-inputs"}
    = f.input :name
    = f.input :network
    = f.input :features
    = f.input :weight
    = f.input :size
    = f.input :akkum
    = f.input :limited
    = f.input :notes
    = f.input :photo_url

  div{class="form-actions"}
    = f.button :submit

app/views/phones_wiki/brands.html.slim
h3 Brands

ul.list
  - for brand in @brands
    li
      = link_to brand.name, phones_path(brand)

app/views/phones_wiki/edit.html.slim
h1
  |Editing phone 
  = @phone.name

== render 'form'

= link_to 'Destroy', destroy_phone_path(@brand, @phone), method: :delete
|  | 
= link_to 'Show', phone_path(@brand, @phone)
|  | 
= link_to 'Back', phones_path(@brand)

app/views/phones_wiki/new.html.slim
h1 New phone

== render 'form'

= link_to 'Back', phones_path(@brand)

app/views/phones_wiki/phones.html.slim
h3 Phones

#phones_list
  input.search placeholder="Search"

  br
  | Thanks to 
  a href="http://www.siesam.de" Sascha Meuter
  |  for phones list.
  ul.list
    - for phone in @phones
      li
        p.name = link_to phone.name, phone_path(@brand, phone)

br

app/views/phones_wiki/show.html.slim
= link_to 'Back to phones list', phones_path(@brand)

h3
  = @phone.name
  = link_to edit_phone_path(@brand, @phone)
    span{class="glyphicon glyphicon-edit"}

img{src="#{@phone.photo_url}" class="phone_image"}

p
  strong Network:
  = @phone.network

p
  strong Features:
  = @phone.features

p
  strong Weight:
  = @phone.weight

p
  strong Size:
  = @phone.size

p
  strong Akkum:
  = @phone.akkum

p
  strong Limited:
  = @phone.limited

br
p
  strong Notes:
  br
  = raw @phone.notes


- if signed_in?
  = link_to 'Add to collection', new_user_users_phones_path(user_id: current_user.id, phone_id: @phone.id)
  br
  br
  = link_to 'Edit', edit_phone_path(@phone) 